### ISSUE TITLE
Incompatible options allowed

### ISSUE THREAD

**Issue by Tattoo** [JarLoz/TableflipperExtreme#3]
Using options `--hires` and `--imgur` together leads to:

```
Traceback (most recent call last):
  File "flipper.py", line 163, in <module>
    sys.exit(main())
  File "flipper.py", line 56, in main
    generate(args.input, deckName, hires, reprint, nocache, imgur, dropbox, output, basicSet)
  File "flipper.py", line 76, in generate
    ttsJson = converter.convertDecklistToJSON(decklist, deckName, hires, reprint, nocache, imgurId, dropboxToken, output, basicSet)
  File "/Users/tkairi/TableflipperExtreme/deckconverter/converter.py", line 24, in convertDecklistToJSON
    deckObjects.append(generateDeckObjectFromProcessedDecklist(processedDecklist, deckName, posX, hires, imgurId=imgurId, dropboxToken=dropboxToken, output=output))
  File "/Users/tkairi/TableflipperExtreme/deckconverter/converter.py", line 43, in generateDeckObjectFromProcessedDecklist
    deckObject = createDeckObject(processedDecklist, deckName, deckImageNames, posX, output, imgurId, dropboxToken)
  File "/Users/tkairi/TableflipperExtreme/deckconverter/converter.py", line 85, in createDeckObject
    faceUrl = getDeckUrl(deckImageName[0], output, imgurId, dropboxToken)
  File "/Users/tkairi/TableflipperExtreme/deckconverter/converter.py", line 104, in getDeckUrl
    return uploadToImgur(deckImage, imgurId, output)
  File "/Users/tkairi/TableflipperExtreme/deckconverter/converter.py", line 113, in uploadToImgur
    response = client.upload(imageFp)
  File "/usr/local/lib/python3.6/site-packages/gimgurpython/client.py", line 598, in upload
    return self.make_request('POST', 'upload', data, anon)
  File "/usr/local/lib/python3.6/site-packages/gimgurpython/client.py", line 161, in make_request
    raise ImgurClientError(response_data['data']['error'], response.status_code)
gimgurpython.helpers.error.ImgurClientError: (413) File is over the size limit
```

It would be a bit nicer UX if the application would out-right warn me about incompatible options.

**Comment by JarLoz** [comment]
Fixed
